import { existsSync, mkdirSync, readdirSync, rmSync, statSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { picoSupplierIdentifierPattern } from '@pico/protocol/supplier';

/**
 * ADR 0143 DP8 - a workspace, not a store.
 *
 * An extractor unpacking a 1.4 GB corpus needs somewhere to put things. That
 * somewhere must not become a place Pico keeps anything, because ADR 0127's
 * rule that a supplier owns no storage would otherwise be true only until the
 * first supplier needed a temporary file.
 *
 * So the scratch area is defined by what it is **not**:
 *
 * - **not a durable store.** It is absent from `picoDurableStores`, which
 *   means no ADR 0119 Q5 ceiling, no place in the shred cascade, no backup
 *   exclusion to maintain and no Q3 byte-identity obligation - the five
 *   questions ADR 0129 SR2 asks of a new store kind are not answered here
 *   because there is nothing to answer them about. A test asserts the absence
 *   rather than trusting the reading.
 * - **not backed up.** ADR 0110's backup covers the database; nothing here is
 *   in it, and nothing here would be worth restoring - a half-unpacked corpus
 *   is regenerated by asking again.
 * - **not the supplier's to choose.** A supplier is handed a path in a
 *   request, the way `git-library` is handed a working copy. There is no
 *   parameter through which it names its own directory, which is why an
 *   identifier is validated against ADR 0137 IN1's pattern here: a supplier
 *   whose identifier could contain a slash would be a supplier that chose a
 *   path.
 *
 * **Removal is reconciled rather than trusted.** `detach` deletes the
 * directory, and `removeOrphans` deletes every directory with no attachment
 * behind it. A detach that crashed between the row and the files would
 * otherwise leave a person's material on disk after they had detached the
 * thing that put it there - and that is the failure worth designing against,
 * because the person believes it is gone. Same posture as ADR 0070's tombstone
 * reconciliation: the durable record decides, and the filesystem is brought
 * back to it.
 */
export class PicoSupplierScratch {
  public constructor(private readonly root: string) {
    if (typeof root !== 'string' || root.trim() === '') {
      throw new Error('invalid_pico_supplier_scratch_root');
    }
  }

  /**
   * The default beside the database, in the idiom `keys`, `home-host-keys`,
   * `backups`, `recovery-anchor` and `depots` already use.
   *
   * Being transient does not make it homeless: something has to pick a place,
   * and picking a different *shape* than the five beside it would be the only
   * decision here worth calling one.
   */
  public static defaultRoot(databasePath: string): string {
    return join(dirname(databasePath), 'scratch');
  }

  /**
   * The directory for one attachment. Validated rather than joined blindly:
   * an identifier is a person-chosen token under ADR 0137 IN1, and the one
   * thing it must never be is a path.
   */
  public pathFor(identifier: string): string {
    if (typeof identifier !== 'string'
      || !picoSupplierIdentifierPattern.test(identifier)) {
      throw new Error('invalid_pico_supplier_identifier');
    }
    const path = resolve(join(this.root, identifier));
    if (!path.startsWith(`${resolve(this.root)}/`)) {
      // Unreachable through the pattern above, and kept because this is the
      // boundary where a mistake becomes a directory somewhere else.
      throw new Error('pico_supplier_scratch_escapes_root');
    }
    return path;
  }

  /** Creates the directory if it is missing, and returns it either way. */
  public ensure(identifier: string): string {
    const path = this.pathFor(identifier);
    // Befund B120: dieselbe Frage wie bei der Datenbank daneben - wer darf das
    // lesen. Bisher stand hier die Vorgabe, also 0755 unter der Maske.
    mkdirSync(path, { recursive: true, mode: 0o700 });
    return path;
  }

  /**
   * ADR 0143 DP8. Removes the workspace and everything in it.
   *
   * Deletes rather than shreds, deliberately. Crypto-shredding is for content
   * under ADR 0072 custody; this holds intermediate files nobody decided to
   * keep, and treating it as custody would mean claiming a guarantee -
   * unrecoverable erasure - that a temporary directory on an ordinary
   * filesystem cannot make.
   */
  public detach(identifier: string): void {
    rmSync(this.pathFor(identifier), { recursive: true, force: true });
  }

  /**
   * ADR 0143 DP8. Brings the filesystem back to what the attachment records
   * say, and returns what it removed.
   *
   * This is the half that makes "removed with the attachment" true rather than
   * intended. A detach interrupted between the row and the files would leave a
   * person's material on disk after they detached the thing that put it there,
   * and they would believe it was gone.
   *
   * A directory whose name is not a valid identifier is removed too: nothing
   * this class creates can have such a name, so its presence means something
   * else wrote into the scratch root, and leaving it would make the root a
   * place where unaccounted material accumulates.
   */
  public removeOrphans(attached: readonly string[]): readonly string[] {
    if (!existsSync(this.root) || !statSync(this.root).isDirectory()) {
      return Object.freeze([]);
    }
    const keep = new Set(attached);
    const removed: string[] = [];
    for (const entry of readdirSync(this.root, { withFileTypes: true })) {
      if (keep.has(entry.name) && picoSupplierIdentifierPattern.test(entry.name)) {
        continue;
      }
      rmSync(join(this.root, entry.name), { recursive: true, force: true });
      removed.push(entry.name);
    }
    return Object.freeze(removed.sort());
  }
}
